version: '3'
services:
  frontend:
    build:
      context: ./hotel-frontend
      dockerfile: dockerfile
    ports:
      - "8081:80"
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"